### ISSUE TITLE
Multiple Pickers

### ISSUE THREAD

**Issue by NRDay** [artf/grapick#1]
Great tool. Is it possible to have multiple pickers on the same page?

**Comment by artf** [comment]
Sure, just create another instance
```js
const gp = new Grapick({el: '#gp'});
...
const gp2 = new Grapick({el: '#gp2'});
```

**Comment by NRDay** [comment]
Okay thanks. I'm not sure that will work for me though - the inputs are generated dynamically, with an infinite number of rows, so I need to be able to use dynamically generated IDs. I could I guess output script tag with the js for each input as it's generated. However that seems very inefficient as they all require the same options.

**Comment by artf** [comment]
> so I need to be able to use dynamically generated IDs

Honestly, I don't understand where is the problem, you can also pass the `HTMLElement` if you want

> I could I guess output script tag with the js for each input as it's generated. However that seems very inefficient as they all require the same options.

Just pass the same object and extend only the `el`

```js
new Grapick(Object.assign({}, optionsForAll, {el: '#YourDynamicID'}));
```

**Comment by jloguercio** [comment]
Hi, there is no class selector for multiple instances?
