### ISSUE TITLE
Touch support

### ISSUE THREAD

**Issue by av01d** [artf/grapick#2]
Have you tested this on touch devices? On an iPad, it doesn't really work. You can't move the color stops. I see touch events being used in the source code, but they don't seem to work.
Can you please take a look? Grapick is awesome!

**Comment by Beherith** [comment]
Ive played around with this, and though its not immedately apparent, you can move the color handles:
Touch a color handler to select it, its bar turns white. Touch anywhere to move the color handle there.
Touch it again to deselect it. A bit fiddly, but it works. Tested on android chrome.

**Comment by av01d** [comment]
I've managed to add decent, real, working touch support myself.
Here it is: https://www.dropbox.com/s/s48sp3zdz38wp6i/grapick.js?dl=0
All changes are clearly marked with 'ARJAN' (my name).
Hope you can make some time to adapt those changes in grapick. Thanks!
