### ISSUE TITLE
getColorValueAsArray?

### ISSUE THREAD

**Issue by av01d** [artf/grapick#3]
The `getColorValue` method currently returns a string. That's great for CSS, but I'm using Grapick to create gradients for a canvas: `gradient.addColorStop(color, pos)`, where pos is a float between 0 and 1 (opposed to an integer between 0 and 100).
Can you add a method that allows for retrieving colorstops as an array of objects?
A function that returns something like this?
```
[{color:'rgba(0,0,0,1)',pos:0}, {color:'rgba(0,255,0,1)',pos:50}, {color:'rgba(255,0,0,1),pos:100}
```

Thanks for considering!

**Comment by artf** [comment]
I know I'm a bit late here, but I'd leave this for others
```js
grapickInstance.getHandlers().map(handler => handler.toJSON())
```
All other Handler's API (Handler is the color stop) could be found [here](https://github.com/artf/grapick/wiki#handler)
