### ISSUE TITLE
Clicking on the very bottom of picker adds a transparent  handler

### ISSUE THREAD

**Issue by ghost** [artf/grapick#6]
Able to replicate in Chrome and Firefox, while on Edge I'm not able to select the lowset pixel, as if Chrome or Firefox has extra 1 pixel at the bottom

![image](https://user-images.githubusercontent.com/40167809/58246108-213bd080-7d4e-11e9-9582-4267381277c7.png)

**Comment by kkaminski-github** [comment]
Simple solution is to add extra constraint in initEvents method

```
      const x = e.offsetX - pEl.clientLeft;
      const y = e.offsetY - pEl.clientTop;
      percentage = x / elDim.w * 100;
      if (percentage > max || percentage < min) {
        return;
      }
      if(y > elDim.h || y < 0){
        return;
      }
```
