### ISSUE TITLE
How to preset the value from element css into the grapick?

### ISSUE THREAD

**Issue by abzal0** [artf/grapick#8]
How to set the values for colorEl, min,max,direction from the div element?
For example, 
```

<div id="somegradient" style="background: -webkit-linear-gradient(90deg, rgb(254, 255, 0) 3.1348%, rgb(173, 255, 187) 49.5298%, rgb(251, 163, 150) 97.4922%)">
</div>

<script>
var gradient = $("#somegradient").css('background');
//now how to set this value into the grapick? 
</script>
```

Should I use regex to break down the 
` -webkit-linear-gradient(90deg, rgb(254, 255, 0) 3.1348%, rgb(173, 255, 187) 49.5298%, rgb(251, 163, 150) 97.4922%)`
and then set them with:  
` gp.addHandler(0, 'red');
`

is there direct way of doing this as:
```

<script>
var gradient = $("#somegradient").css('background');
gp.setValue(gradient);
</script>
```

**Comment by cannap** [comment]
hi do you have a solution for this?

**Comment by abzal0** [comment]
> hi do you have a solution for this?

turns out the answer is in the question, you can just call setValue function like this:
 

`var gradient = $(this).css('backgroundImage');
if(gradient !== '' || gradient !== null )
{ gp.setValue(gradient); //value is set 
var grtype = gp.getType(); 
var grdirection = gp.getDirection(); 
$("#switchtype").val(grtype); 
$("#switchangle").val(grdirection); 
}`
